steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/cloud-security-491400/livemenu/frontend',
      '.'
    ]

- name: 'aquasec/trivy'
  args:
    [
      'image',
      '--exit-code',
      '1',
      '--severity',
      'HIGH,CRITICAL',
      'us-central1-docker.pkg.dev/cloud-security-491400/livemenu/frontend'
    ]

images:

- us-central1-docker.pkg.dev/cloud-security-491400/livemenu/frontend
